name: Deploy Helper
on: [push]
jobs:
  Cpoy-Index-To-Cyon:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
      - name: Deployment
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."