name: Deploy Helper
on: [push]
jobs:
  Cpoy-Index-To-Cyon:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: eval $(ssh-agent)
      - run: echo "${{ secrets.cyon_deployment }}" | tr -d '\r' | ssh-add - > /dev/null
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: ssh-keyscan $DEPLOY_IP >> ~/.ssh/known_hosts
      - run: chmod 644 ~/.ssh/known_hosts
